### ISSUE TITLE
in what order should the scripts be executed?

### ISSUE THREAD

**Issue by frederic-mahe** [Marilyne-AzaGnandji/PHD_Project_Scripts#1]
it is not clear for potential users what is the first script to execute, what are the dependencies, what needs to be done before starting, etc.

**Comment by Marilyne-AzaGnandji** [comment]
I will add another script for softwares and their dependencies downloading/installation...

**Comment by frederic-mahe** [comment]
keep the issue open until it is actually solved.

**Comment by Marilyne-AzaGnandji** [comment]
Okay

**Comment by Marilyne-AzaGnandji** [comment]
@frederic-mahe You mean to number my scripts?

**Comment by frederic-mahe** [comment]
Try something that seems logical to you. If necessary, I will suggest something else.
