### ISSUE TITLE
if multiqc is not available, should the script continue to execute?

### ISSUE THREAD

**Issue by frederic-mahe** [Marilyne-AzaGnandji/PHD_Project_Scripts#2]
https://github.com/Marilyne-AzaGnandji/PHD_Project_Scripts/blob/c4373ca362c65875dfe848ea35d93d94a954e5e1/1.FasqcMultiqc.sh#L6

**Comment by Marilyne-AzaGnandji** [comment]
I think yes but until the step of quality control performing with multiqc...
This software (multiqc) is supposed to be available with the first file "Softwares_Installation.sh" execution...Or it's not what you mean?

**Comment by frederic-mahe** [comment]
It would be safer to abort immediately if a key-software is missing.

**Comment by Marilyne-AzaGnandji** [comment]
@frederic-mahe okay
